---
- name: "Get checksum list"
  ansible.builtin.set_fact:
    __alertmanager_checksums: "{{ lookup('url', alertmanager_checksums_url, headers=_github_api_headers, wantlist=True) | list }}"
  run_once: true
  until: __alertmanager_checksums is search('linux-' + go_arch + '.tar.gz')
  retries: 10

- name: "Get checksum for {{ go_arch }}"
  ansible.builtin.set_fact:
    __alertmanager_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ __alertmanager_checksums }}"
  when:
    - "('linux-' + go_arch + '.tar.gz') in item"
