---
- name: Discover latest version
  ansible.builtin.set_fact:
    snmp_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/prometheus/snmp_exporter/releases/latest', headers=_github_api_headers,
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: snmp_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - snmp_exporter_version == "latest"
    - snmp_exporter_binary_local_dir | length == 0
    - not snmp_exporter_skip_install

- name: Get snmp_exporter binary checksum
  when:
    - snmp_exporter_binary_local_dir | length == 0
    - not snmp_exporter_skip_install
  ansible.builtin.include_tasks:
    file: get_checksum.yml
