---
- name: "Get checksum list"
  ansible.builtin.set_fact:
    __prometheus_checksums: "{{ lookup('url', prometheus_checksums_url, headers=_github_api_headers, wantlist=True) | list }}"
  run_once: true
  until: __prometheus_checksums is search('linux-' + go_arch + '.tar.gz')
  retries: 10

- name: "Get checksum for {{ go_arch }}"
  ansible.builtin.set_fact:
    __prometheus_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ __prometheus_checksums }}"
  when:
    - "('linux-' + go_arch + '.tar.gz') in item"
