---
- name: Get checksum list from github
  ansible.builtin.set_fact:
    __smokeping_prober_checksums: "{{ lookup('url', smokeping_prober_checksums_url, headers=_github_api_headers, wantlist=True) | list }}"
  run_once: true
  until: __smokeping_prober_checksums is search('linux-' + go_arch + '.tar.gz')
  retries: 10

- name: "Get checksum for {{ go_arch }}"
  ansible.builtin.set_fact:
    __smokeping_prober_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ __smokeping_prober_checksums }}"
  when:
    - "('linux-' + go_arch + '.tar.gz') in item"
